name: "Entregables"

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - deliverables
jobs:
  entregables:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Deliverables
        run: |
          ls -la .github
          python3 .github/code/check.py
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push          
