name: "Prediction"

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - deliverables
jobs:
  yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Deliverables
        run: |
          python3 PetProject/quinielas.py
